MODEL:
  TYPE: ResNet
  IMG_SIZE: 32 
  NUM_CLASSES: 4
CNN:
  DEPTH: 56
RESNET:
  TRANS_FUN: basic_transform
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: chaoyang
  SPLIT: train
  BATCH_SIZE: 64
TEST:
  DATASET: chaoyang
  SPLIT: test
  BATCH_SIZE: 64
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: False
